# Generated by Django 2.2.11 on 2020-03-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uPlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('rawJson', models.CharField(max_length=15000)),
            ],
        ),
    ]
