# Generated by Django 2.2.11 on 2020-03-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uPlan', '0002_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='crn_filed',
            new_name='crn_field',
        ),
    ]
