# Generated by Django 2.2.11 on 2020-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uPlan', '0003_auto_20200323_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(max_length=200),
        ),
    ]
